---

port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: / ## disables post output
timezone: null
lsi: false
markdown: kramdown
highlighter: pygments


### content configuration ###
title:       "Vuece Apps for Music"
keywords:    "SinglePaged, jekyll, template, github, blog, single page"
description: "A single-page template for Jekyll based blogs (like what you'd use on github pages!)"
source_link: "https://github.com/t413/SinglePaged"
favicon:     "img/applogo_v4_blue_dark.ico"
touch_icon:  "img/Logo_LightBlue.png"
google_analytics_key: "UA-61582007-1" ## put YOUR key here to enable tracking! (blank to disable)

### template colors, used site-wide via css ###
colors:
  black:     '#111111'
  white:     '#f8f8f8'
  blue:      '#49a7e9'
  green:     '#bccf02'
  purple:    '#c869bf'
  orange:    '#fab125'
  yellow:    '#FFFF00'
  turquoise: '#0fbfcf'
  vuece_pink_dark: rgb(255, 102, 102)
  funk_yellow: '#fff200'
  aqua: '#00FFFF'
  scheme1_black: '#393939'
  scheme1_dark_black: '#111111'
  scheme1_orange: '#FF5A09'
  scheme1_pink: '#F3843E'
  scheme1_yellow: '#ff9900'
  scheme1_yellow_bright: '#fee202'
  scheme1_gray: '#6e6e6e'
  scheme1_dark_blue: '#004687'
  scheme1_choc: '#48372f'
  vuece_black_light: '#393939'
  vuece_blue: '#0193B7'
  
